from util import *
import torch
import torch.nn as nn

class Discriminator(nn.Module):
    """ The disciminator module of the stGAN model will classify whether an input spatial transcriptomics 
        image is real or generated by the generator
    """
    def __init__(self, num_genes, embed_dim):
        super(Discriminator, self).__init__()
        self.num_genes = num_genes
        self.embed_dim = embed_dim

        self.fc1= nn.Linear(self.num_genes, embed_dim)
        self.fc2 = nn.Linear(self.embed_dim, 1)

        self.activation = nn.ReLU()

    def forward(self, input_data):
        input_data = input_data.to(device)
        outs = None
        outs = self.fc1(input_data)
        outs = self.activation(outs)
        outs = self.fc2(outs)
        return torch.sigmoid(outs)